"""Module Documentation here

"""
#=========================================================================================
# Licence, Reference and Credits
#=========================================================================================
__copyright__ = "Copyright (C) CCPN project (www.ccpn.ac.uk) 2014 - $Date$"
__credits__ = "Wayne Boucher, Rasmus H Fogh, Simon P Skinner, Geerten W Vuister"
__license__ = ("CCPN license. See www.ccpn.ac.uk/license"
              "or ccpnmodel.ccpncore.memops.Credits.CcpnLicense for license text")
__reference__ = ("For publications, please use reference from www.ccpn.ac.uk/license"
                " or ccpnmodel.ccpncore.memops.Credits.CcpNmrReference")

#=========================================================================================
# Last code modification:
#=========================================================================================
__author__ = "$Author$"
__date__ = "$Date$"
__version__ = "$Revision$"

#=========================================================================================
# Start of code
#=========================================================================================
""" Generate autogenerated files from model
All data are read from and written to a file tree of the structure given by
the code repository.
Default is to use the same file tree as the code is loaded from,
determined as the tree that contains memops.universal.constants.

======================COPYRIGHT/LICENSE START==========================

makePython.py: Code generation for CCPN framework

Copyright (C) 2005 Rasmus Fogh (CCPN Project)

=======================================================================

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public
License as published by the Free Software Foundation; either
version 2 of the License, or (at your option) any later version.
 
A copy of this license can be found in ../../../license/GPL.license
 
This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
General Public License for more details.
 
You should have received a copy of the GNU General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA


======================COPYRIGHT/LICENSE END============================

for further information, please contact :

- CCPN website (http://www.ccpn.ac.uk/)

- email: ccpn@bioc.cam.ac.uk

=======================================================================

If you are using this software for academic purposes, we suggest
quoting the following references:

===========================REFERENCE START=============================
R. Fogh, J. Ionides, E. Ulrich, W. Boucher, W. Vranken, J.P. Linge, M.
Habeck, W. Rieping, T.N. Bhat, J. Westbrook, K. Henrick, G. Gilliland,
H. Berman, J. Thornton, M. Nilges, J. Markley and E. Laue (2002). The
CCPN project: An interim report on a data model for the NMR community
(Progress report). Nature Struct. Biol. 9, 416-418.

Rasmus H. Fogh, Wayne Boucher, Wim F. Vranken, Anne
Pajon, Tim J. Stevens, T.N. Bhat, John Westbrook, John M.C. Ionides and
Ernest D. Laue (2005). A framework for scientific data modeling and automated
software development. Bioinformatics 21, 1678-1684.

===========================REFERENCE END===============================
"""

import time

from ccpn.core.lib import Documentation
from ccpnmodel.ccpncore.memops.scripts.docgen import PyApiDocGen
from ccpnmodel.ccpncore.memops.scripts.makePython import getModelPortal


defaultIgnoreModules = []


def makeSphinxDoc():
  """ Generate Sphinx documentation')
  """

  start = time.time()
  Documentation.refreshSphinxDocumentation()
  end = time.time()
  print("""
  Memops refreshed sphinx documentation, time %s
  """ % (end-start))


def makeApiDoc(modelPortal, rootDirName=None, rootFileName=None,
               releaseVersion=None, ignoreModules=None):
  """ Generate all python relevant code for a version
  - rootDirName: topmost directory to write to (defaults to current cvsroot)
  - rootFileName: file/dir name for root package (defaults to 'RootPackage')
  - releaseVersion: release version object (defaults to  'unknown')
  """

  # generate documentation
  start = time.time()
  PyApiDocGen.writeApiDoc(modelPortal, rootDirName=rootDirName,
    rootFileName=rootFileName, releaseVersion=releaseVersion)
  end = time.time()
  print("""
  Memops done ApiDocGen, time %s
  """ % (end-start))

        

if __name__ == '__main__':
  
  makeSphinxDoc()
  # Temporarily suspended. Do we even distribute it?
  # makeApiDoc(getModelPortal())
