"""
#######################################################################

CCPN Data Model version 3.0.2

Autogenerated by PyXmlMapWrite on Fri Nov 18 11:44:02 2016
  from data model element ccp.molecule.MolSystem

#######################################################################
======================COPYRIGHT/LICENSE START==========================

MolSystem.py: python XML-I/O-mapping for CCPN data model, MetaPackage ccp.molecule.MolSystem

Copyright (C) 2007  (CCPN Project)

=======================================================================

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

A copy of this license can be found in ../../../../../../../license/LGPL.license

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA


======================COPYRIGHT/LICENSE END============================

for further information, please contact :

- CCPN website (http://www.ccpn.ac.uk/)

- email: ccpn@bioc.cam.ac.uk

=======================================================================

If you are using this software for academic purposes, we suggest
quoting the following references:

===========================REFERENCE START=============================
Rasmus H. Fogh, Wayne Boucher, Wim F. Vranken, Anne
Pajon, Tim J. Stevens, T.N. Bhat, John Westbrook, John M.C. Ionides and
Ernest D. Laue (2005). A framework for scientific data modeling and automated
software development. Bioinformatics 21, 1678-1684.


This file was generated with the Memops software generation framework,
and contains original contributions embedded in the framework

===========================REFERENCE END===============================
"""

from ccpnmodel.ccpncore.memops.metamodel.Constants import baseDataTypeModule as basicDataTypes
NaN = float('NaN')
# 
#  Current package api
import ccpnmodel.ccpncore.api.ccp.molecule.MolSystem

def makeMapping(globalMap):
  """
  generates XML I/O mapping for package MOLS, adding it to globalMap
  """
  
  from ccpnmodel.ccpncore.xml.memops.Implementation import bool2str, str2bool

  # Set up top level dictionaries
  loadMaps = globalMap.get('loadMaps')
  mapsByGuid = globalMap.get('mapsByGuid')

  abstractTypes = globalMap.get('MOLS').get('abstractTypes')
  exolinks = globalMap.get('MOLS').get('exolinks')

  # DataType AtomType
  currentMap = {}
  abstractTypes['AtomType'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2014-07-31-11:44:56_00002'] = currentMap
  loadMaps['MOLS.AtomType'] = currentMap
  currentMap['tag'] = 'MOLS.AtomType'
  currentMap['type'] = 'simple'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2014-07-31-11:44:56_00002'
  currentMap['toStr'] = 'text'
  currentMap['cnvrt'] = 'text'

  # Class Atom
  currentMap = {}
  abstractTypes['Atom'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-14:22:54_00029'] = currentMap
  loadMaps['MOLS.Atom'] = currentMap
  currentMap['tag'] = 'MOLS.Atom'
  currentMap['type'] = 'class'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-14:22:54_00029'
  currentMap['eType'] = 'cplx'
  currentMap['fromParent'] = 'atoms'
  currentMap['objkey'] = 'name'
  currentMap['class'] = ccpnmodel.ccpncore.api.ccp.molecule.MolSystem.Atom
  contentMap = {}
  currentMap['content'] = contentMap

  # Attribute Atom._ID
  contentMap['_ID'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2014-03-03-16:24:15_00001')

  # Attribute Atom.applicationData
  contentMap['applicationData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-09-14-18:48:27_00007')

  # Attribute Atom.atomSetName
  currentMap = {}
  contentMap['atomSetName'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2014-09-09-11:30:10_00002'] = currentMap
  loadMaps['MOLS.Atom.atomSetName'] = currentMap
  currentMap['tag'] = 'MOLS.Atom.atomSetName'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2014-09-09-11:30:10_00002'
  currentMap['name'] = 'atomSetName'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00037')

  # Attribute Atom.atomType
  currentMap = {}
  contentMap['atomType'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2014-07-31-11:46:10_00003'] = currentMap
  loadMaps['MOLS.Atom.atomType'] = currentMap
  currentMap['tag'] = 'MOLS.Atom.atomType'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2014-07-31-11:46:10_00003'
  currentMap['name'] = 'atomType'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['default'] = 'single'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2014-07-31-11:44:56_00002')

  # Attribute Atom.ccpnInternalData
  contentMap['ccpnInternalData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2016-06-28-10:49:27_00001')

  # Attribute Atom.elementSymbol
  currentMap = {}
  contentMap['elementSymbol'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2014-09-09-11:30:10_00001'] = currentMap
  loadMaps['MOLS.Atom.elementSymbol'] = currentMap
  currentMap['tag'] = 'MOLS.Atom.elementSymbol'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2014-09-09-11:30:10_00001'
  currentMap['name'] = 'elementSymbol'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00037')

  # Attribute Atom.name
  currentMap = {}
  contentMap['name'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:32_00029'] = currentMap
  loadMaps['MOLS.Atom.name'] = currentMap
  currentMap['tag'] = 'MOLS.Atom.name'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:32_00029'
  currentMap['name'] = 'name'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00037')

  # Role Atom.atomGroups
  currentMap = {}
  contentMap['atomGroups'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2014-07-31-11:46:10_00001'] = currentMap
  loadMaps['MOLS.Atom.atomGroups'] = currentMap
  currentMap['tag'] = 'MOLS.Atom.atomGroups'
  currentMap['type'] = 'link'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2014-07-31-11:46:10_00001'
  currentMap['name'] = 'atomGroups'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['copyOverride'] = True

  # Role Atom.boundAtoms
  currentMap = {}
  contentMap['boundAtoms'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2014-07-31-11:45:35_00002'] = currentMap
  loadMaps['MOLS.Atom.boundAtoms'] = currentMap
  currentMap['tag'] = 'MOLS.Atom.boundAtoms'
  currentMap['type'] = 'link'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2014-07-31-11:45:35_00002'
  currentMap['name'] = 'boundAtoms'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['copyOverride'] = True

  # Role Atom.components
  currentMap = {}
  contentMap['components'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2014-07-31-11:46:10_00002'] = currentMap
  loadMaps['MOLS.Atom.components'] = currentMap
  currentMap['tag'] = 'MOLS.Atom.components'
  currentMap['type'] = 'link'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2014-07-31-11:46:10_00002'
  currentMap['name'] = 'components'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['copyOverride'] = True

  # Role Atom.genericBonds
  currentMap = {}
  contentMap['genericBonds'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:33_00042'] = currentMap
  loadMaps['MOLS.Atom.genericBonds'] = currentMap
  currentMap['tag'] = 'MOLS.Atom.genericBonds'
  currentMap['type'] = 'link'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:33_00042'
  currentMap['name'] = 'genericBonds'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['copyOverride'] = False
  # End of Atom

  currentMap = abstractTypes.get('Atom')
  aList = ['_ID', 'atomSetName', 'atomType', 'elementSymbol', 'name']
  currentMap['headerAttrs'] = aList
  aList = ['ccpnInternalData', 'atomGroups', 'boundAtoms', 'components', 'genericBonds']
  currentMap['simpleAttrs'] = aList
  aList = ['applicationData']
  currentMap['cplxAttrs'] = aList

  # Class Chain
  currentMap = {}
  abstractTypes['Chain'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-14:22:54_00024'] = currentMap
  loadMaps['MOLS.Chain'] = currentMap
  currentMap['tag'] = 'MOLS.Chain'
  currentMap['type'] = 'class'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-14:22:54_00024'
  currentMap['eType'] = 'cplx'
  currentMap['fromParent'] = 'chains'
  currentMap['objkey'] = 'code'
  currentMap['class'] = ccpnmodel.ccpncore.api.ccp.molecule.MolSystem.Chain
  contentMap = {}
  currentMap['content'] = contentMap

  # Attribute Chain._ID
  contentMap['_ID'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2014-03-03-16:24:15_00001')

  # Attribute Chain.applicationData
  contentMap['applicationData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-09-14-18:48:27_00007')

  # Attribute Chain.ccpnInternalData
  contentMap['ccpnInternalData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2016-06-28-10:49:27_00001')

  # Attribute Chain.chemExchangeState
  currentMap = {}
  contentMap['chemExchangeState'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:32_00009'] = currentMap
  loadMaps['MOLS.Chain.chemExchangeState'] = currentMap
  currentMap['tag'] = 'MOLS.Chain.chemExchangeState'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:32_00009'
  currentMap['name'] = 'chemExchangeState'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033')

  # Attribute Chain.code
  currentMap = {}
  contentMap['code'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:32_00002'] = currentMap
  loadMaps['MOLS.Chain.code'] = currentMap
  currentMap['tag'] = 'MOLS.Chain.code'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:32_00002'
  currentMap['name'] = 'code'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033')

  # Attribute Chain.conformationalIsomer
  currentMap = {}
  contentMap['conformationalIsomer'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:32_00008'] = currentMap
  loadMaps['MOLS.Chain.conformationalIsomer'] = currentMap
  currentMap['tag'] = 'MOLS.Chain.conformationalIsomer'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:32_00008'
  currentMap['name'] = 'conformationalIsomer'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033')

  # Attribute Chain.details
  currentMap = {}
  contentMap['details'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:32_00013'] = currentMap
  loadMaps['MOLS.Chain.details'] = currentMap
  currentMap['tag'] = 'MOLS.Chain.details'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:32_00013'
  currentMap['name'] = 'details'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['proc'] = 'direct'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00035')

  # Attribute Chain.magnEquivalenceCode
  currentMap = {}
  contentMap['magnEquivalenceCode'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:32_00006'] = currentMap
  loadMaps['MOLS.Chain.magnEquivalenceCode'] = currentMap
  currentMap['tag'] = 'MOLS.Chain.magnEquivalenceCode'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:32_00006'
  currentMap['name'] = 'magnEquivalenceCode'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033')

  # Attribute Chain.pdbOneLetterCode
  currentMap = {}
  contentMap['pdbOneLetterCode'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:32_00003'] = currentMap
  loadMaps['MOLS.Chain.pdbOneLetterCode'] = currentMap
  currentMap['tag'] = 'MOLS.Chain.pdbOneLetterCode'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:32_00003'
  currentMap['name'] = 'pdbOneLetterCode'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['eType'] = 'cplx'
  currentMap['default'] = ' '
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033')

  # Attribute Chain.physicalState
  currentMap = {}
  contentMap['physicalState'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:32_00007'] = currentMap
  loadMaps['MOLS.Chain.physicalState'] = currentMap
  currentMap['tag'] = 'MOLS.Chain.physicalState'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:32_00007'
  currentMap['name'] = 'physicalState'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033')

  # Attribute Chain.role
  currentMap = {}
  contentMap['role'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:32_00005'] = currentMap
  loadMaps['MOLS.Chain.role'] = currentMap
  currentMap['tag'] = 'MOLS.Chain.role'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:32_00005'
  currentMap['name'] = 'role'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033')

  # Role Chain.chainFragments
  currentMap = {}
  contentMap['chainFragments'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:32_00001'] = currentMap
  loadMaps['MOLS.Chain.chainFragments'] = currentMap
  currentMap['tag'] = 'MOLS.Chain.chainFragments'
  currentMap['type'] = 'child'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:32_00001'
  currentMap['name'] = 'chainFragments'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['content'] = globalMap.get('MOLS').get('abstractTypes')

  # Role Chain.chainGroups
  currentMap = {}
  contentMap['chainGroups'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2016-09-12-10:13:31_00002'] = currentMap
  loadMaps['MOLS.Chain.chainGroups'] = currentMap
  currentMap['tag'] = 'MOLS.Chain.chainGroups'
  currentMap['type'] = 'link'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2016-09-12-10:13:31_00002'
  currentMap['name'] = 'chainGroups'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['copyOverride'] = True

  # Role Chain.chainInteractions
  currentMap = {}
  contentMap['chainInteractions'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:32_00021'] = currentMap
  loadMaps['MOLS.Chain.chainInteractions'] = currentMap
  currentMap['tag'] = 'MOLS.Chain.chainInteractions'
  currentMap['type'] = 'link'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:32_00021'
  currentMap['name'] = 'chainInteractions'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['copyOverride'] = False

  # Role Chain.molecule
  currentMap = {}
  contentMap['molecule'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:33_00044'] = currentMap
  loadMaps['MOLS.Chain.molecule'] = currentMap
  currentMap['tag'] = 'MOLS.Chain.molecule'
  currentMap['type'] = 'exotop'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:33_00044'
  currentMap['name'] = 'molecule'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['eType'] = 'cplx'
  currentMap['copyOverride'] = True
  currentMap['content'] = globalMap.get('MOLE').get('exolinks')

  # Role Chain.residues
  currentMap = {}
  contentMap['residues'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:31_00036'] = currentMap
  loadMaps['MOLS.Chain.residues'] = currentMap
  currentMap['tag'] = 'MOLS.Chain.residues'
  currentMap['type'] = 'child'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:31_00036'
  currentMap['name'] = 'residues'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['content'] = globalMap.get('MOLS').get('abstractTypes')
  # End of Chain

  currentMap = abstractTypes.get('Chain')
  aList = ['_ID']
  currentMap['headerAttrs'] = aList
  aList = ['ccpnInternalData', 'chemExchangeState', 'code', 'conformationalIsomer', 'details', 'magnEquivalenceCode', 'pdbOneLetterCode', 'physicalState', 'role', 'chainGroups', 'chainInteractions']
  currentMap['simpleAttrs'] = aList
  aList = ['residues', 'chainFragments', 'molecule', 'applicationData']
  currentMap['cplxAttrs'] = aList
  aList = ['chainFragments', 'residues']
  currentMap['children'] = aList

  # Class ChainFragment
  currentMap = {}
  abstractTypes['ChainFragment'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-14:22:54_00036'] = currentMap
  loadMaps['MOLS.ChainFragment'] = currentMap
  currentMap['tag'] = 'MOLS.ChainFragment'
  currentMap['type'] = 'class'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-14:22:54_00036'
  currentMap['eType'] = 'cplx'
  currentMap['fromParent'] = 'chainFragments'
  currentMap['objkey'] = 'serial'
  currentMap['class'] = ccpnmodel.ccpncore.api.ccp.molecule.MolSystem.ChainFragment
  contentMap = {}
  currentMap['content'] = contentMap

  # Attribute ChainFragment._ID
  contentMap['_ID'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2014-03-03-16:24:15_00001')

  # Attribute ChainFragment.applicationData
  contentMap['applicationData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-09-14-18:48:27_00007')

  # Attribute ChainFragment.ccpnInternalData
  contentMap['ccpnInternalData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2016-06-28-10:49:27_00001')

  # Attribute ChainFragment.isLinearPolymer
  currentMap = {}
  contentMap['isLinearPolymer'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:33_00041'] = currentMap
  loadMaps['MOLS.ChainFragment.isLinearPolymer'] = currentMap
  currentMap['tag'] = 'MOLS.ChainFragment.isLinearPolymer'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:33_00041'
  currentMap['name'] = 'isLinearPolymer'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00028')

  # Attribute ChainFragment.molType
  currentMap = {}
  contentMap['molType'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:33_00040'] = currentMap
  loadMaps['MOLS.ChainFragment.molType'] = currentMap
  currentMap['tag'] = 'MOLS.ChainFragment.molType'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:33_00040'
  currentMap['name'] = 'molType'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00037')

  # Attribute ChainFragment.serial
  currentMap = {}
  contentMap['serial'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:33_00039'] = currentMap
  loadMaps['MOLS.ChainFragment.serial'] = currentMap
  currentMap['tag'] = 'MOLS.ChainFragment.serial'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:33_00039'
  currentMap['name'] = 'serial'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00032')

  # Role ChainFragment.residues
  currentMap = {}
  contentMap['residues'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:33_00038'] = currentMap
  loadMaps['MOLS.ChainFragment.residues'] = currentMap
  currentMap['tag'] = 'MOLS.ChainFragment.residues'
  currentMap['type'] = 'link'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:33_00038'
  currentMap['name'] = 'residues'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['copyOverride'] = False
  # End of ChainFragment

  currentMap = abstractTypes.get('ChainFragment')
  aList = ['_ID', 'isLinearPolymer', 'molType', 'serial']
  currentMap['headerAttrs'] = aList
  aList = ['ccpnInternalData', 'residues']
  currentMap['simpleAttrs'] = aList
  aList = ['applicationData']
  currentMap['cplxAttrs'] = aList

  # Class ChainGroup
  currentMap = {}
  abstractTypes['ChainGroup'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2016-09-12-10:13:24_00001'] = currentMap
  loadMaps['MOLS.ChainGroup'] = currentMap
  currentMap['tag'] = 'MOLS.ChainGroup'
  currentMap['type'] = 'class'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2016-09-12-10:13:24_00001'
  currentMap['eType'] = 'cplx'
  currentMap['fromParent'] = 'chainGroups'
  currentMap['objkey'] = 'name'
  currentMap['class'] = ccpnmodel.ccpncore.api.ccp.molecule.MolSystem.ChainGroup
  contentMap = {}
  currentMap['content'] = contentMap

  # Attribute ChainGroup._ID
  contentMap['_ID'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2014-03-03-16:24:15_00001')

  # Attribute ChainGroup.applicationData
  contentMap['applicationData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-09-14-18:48:27_00007')

  # Attribute ChainGroup.ccpnInternalData
  contentMap['ccpnInternalData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2016-06-28-10:49:27_00001')

  # Attribute ChainGroup.name
  currentMap = {}
  contentMap['name'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2016-09-12-10:13:31_00003'] = currentMap
  loadMaps['MOLS.ChainGroup.name'] = currentMap
  currentMap['tag'] = 'MOLS.ChainGroup.name'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2016-09-12-10:13:31_00003'
  currentMap['name'] = 'name'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033')

  # Role ChainGroup.chains
  currentMap = {}
  contentMap['chains'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2016-09-12-10:13:31_00001'] = currentMap
  loadMaps['MOLS.ChainGroup.chains'] = currentMap
  currentMap['tag'] = 'MOLS.ChainGroup.chains'
  currentMap['type'] = 'link'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2016-09-12-10:13:31_00001'
  currentMap['name'] = 'chains'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['copyOverride'] = True
  # End of ChainGroup

  currentMap = abstractTypes.get('ChainGroup')
  aList = ['_ID']
  currentMap['headerAttrs'] = aList
  aList = ['ccpnInternalData', 'name', 'chains']
  currentMap['simpleAttrs'] = aList
  aList = ['applicationData']
  currentMap['cplxAttrs'] = aList

  # Class ChainInteraction
  currentMap = {}
  abstractTypes['ChainInteraction'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-14:22:54_00026'] = currentMap
  loadMaps['MOLS.ChainInteraction'] = currentMap
  currentMap['tag'] = 'MOLS.ChainInteraction'
  currentMap['type'] = 'class'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-14:22:54_00026'
  currentMap['eType'] = 'cplx'
  currentMap['fromParent'] = 'chainInteractions'
  currentMap['class'] = ccpnmodel.ccpncore.api.ccp.molecule.MolSystem.ChainInteraction
  contentMap = {}
  currentMap['content'] = contentMap

  # Attribute ChainInteraction._ID
  contentMap['_ID'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2014-03-03-16:24:15_00001')

  # Attribute ChainInteraction.applicationData
  contentMap['applicationData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-09-14-18:48:27_00007')

  # Attribute ChainInteraction.ccpnInternalData
  contentMap['ccpnInternalData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2016-06-28-10:49:27_00001')

  # Attribute ChainInteraction.interactionType
  currentMap = {}
  contentMap['interactionType'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:32_00024'] = currentMap
  loadMaps['MOLS.ChainInteraction.interactionType'] = currentMap
  currentMap['tag'] = 'MOLS.ChainInteraction.interactionType'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:32_00024'
  currentMap['name'] = 'interactionType'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033')

  # Role ChainInteraction.chains
  currentMap = {}
  contentMap['chains'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:32_00022'] = currentMap
  loadMaps['MOLS.ChainInteraction.chains'] = currentMap
  currentMap['tag'] = 'MOLS.ChainInteraction.chains'
  currentMap['type'] = 'link'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:32_00022'
  currentMap['name'] = 'chains'
  currentMap['hicard'] = 2
  currentMap['locard'] = 2
  currentMap['copyOverride'] = True
  # End of ChainInteraction

  currentMap = abstractTypes.get('ChainInteraction')
  aList = ['_ID']
  currentMap['headerAttrs'] = aList
  aList = ['ccpnInternalData', 'interactionType', 'chains']
  currentMap['simpleAttrs'] = aList
  aList = ['applicationData']
  currentMap['cplxAttrs'] = aList

  # Class GenericBond
  currentMap = {}
  abstractTypes['GenericBond'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-14:22:54_00037'] = currentMap
  loadMaps['MOLS.GenericBond'] = currentMap
  currentMap['tag'] = 'MOLS.GenericBond'
  currentMap['type'] = 'class'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-14:22:54_00037'
  currentMap['eType'] = 'cplx'
  currentMap['fromParent'] = 'genericBonds'
  currentMap['class'] = ccpnmodel.ccpncore.api.ccp.molecule.MolSystem.GenericBond
  contentMap = {}
  currentMap['content'] = contentMap

  # Attribute GenericBond._ID
  contentMap['_ID'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2014-03-03-16:24:15_00001')

  # Attribute GenericBond.applicationData
  contentMap['applicationData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-09-14-18:48:27_00007')

  # Attribute GenericBond.bondType
  currentMap = {}
  contentMap['bondType'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2016-01-29-09:12:56_00001'] = currentMap
  loadMaps['MOLS.GenericBond.bondType'] = currentMap
  currentMap['tag'] = 'MOLS.GenericBond.bondType'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2016-01-29-09:12:56_00001'
  currentMap['name'] = 'bondType'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00037')

  # Attribute GenericBond.ccpnInternalData
  contentMap['ccpnInternalData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2016-06-28-10:49:27_00001')

  # Role GenericBond.atoms
  currentMap = {}
  contentMap['atoms'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:33_00043'] = currentMap
  loadMaps['MOLS.GenericBond.atoms'] = currentMap
  currentMap['tag'] = 'MOLS.GenericBond.atoms'
  currentMap['type'] = 'link'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:33_00043'
  currentMap['name'] = 'atoms'
  currentMap['hicard'] = 2
  currentMap['locard'] = 2
  currentMap['copyOverride'] = True
  # End of GenericBond

  currentMap = abstractTypes.get('GenericBond')
  aList = ['_ID', 'bondType']
  currentMap['headerAttrs'] = aList
  aList = ['ccpnInternalData', 'atoms']
  currentMap['simpleAttrs'] = aList
  aList = ['applicationData']
  currentMap['cplxAttrs'] = aList

  # Class MolSystem
  currentMap = {}
  abstractTypes['MolSystem'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-14:22:54_00023'] = currentMap
  loadMaps['MOLS.MolSystem'] = currentMap
  currentMap['tag'] = 'MOLS.MolSystem'
  currentMap['type'] = 'class'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-14:22:54_00023'
  currentMap['eType'] = 'cplx'
  currentMap['fromParent'] = 'molSystems'
  currentMap['isTop'] = True
  currentMap['objkey'] = 'code'
  currentMap['class'] = ccpnmodel.ccpncore.api.ccp.molecule.MolSystem.MolSystem
  contentMap = {}
  currentMap['content'] = contentMap

  # Attribute MolSystem._ID
  contentMap['_ID'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2014-03-03-16:24:15_00001')

  # Attribute MolSystem._lastId
  contentMap['_lastId'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2014-03-05-13:04:27_00001')

  # Attribute MolSystem.applicationData
  contentMap['applicationData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-09-14-18:48:27_00007')

  # Attribute MolSystem.ccpnInternalData
  contentMap['ccpnInternalData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2016-06-28-10:49:27_00001')

  # Attribute MolSystem.code
  currentMap = {}
  contentMap['code'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:31_00019'] = currentMap
  loadMaps['MOLS.MolSystem.code'] = currentMap
  currentMap['tag'] = 'MOLS.MolSystem.code'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:31_00019'
  currentMap['name'] = 'code'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00037')

  # Attribute MolSystem.commonNames
  currentMap = {}
  contentMap['commonNames'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:31_00023'] = currentMap
  loadMaps['MOLS.MolSystem.commonNames'] = currentMap
  currentMap['tag'] = 'MOLS.MolSystem.commonNames'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:31_00023'
  currentMap['name'] = 'commonNames'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00035')

  # Attribute MolSystem.createdBy
  contentMap['createdBy'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-12-31-09:00:59_00002__www.ccpn.ac.uk_Fogh_2007-10-03-14:53:27_00001__www.ccpn.ac.uk_Fogh_2006-09-14-16:28:57_00002')

  # Attribute MolSystem.details
  currentMap = {}
  contentMap['details'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:31_00028'] = currentMap
  loadMaps['MOLS.MolSystem.details'] = currentMap
  currentMap['tag'] = 'MOLS.MolSystem.details'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:31_00028'
  currentMap['name'] = 'details'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['proc'] = 'direct'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00035')

  # Attribute MolSystem.functions
  currentMap = {}
  contentMap['functions'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:31_00025'] = currentMap
  loadMaps['MOLS.MolSystem.functions'] = currentMap
  currentMap['tag'] = 'MOLS.MolSystem.functions'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:31_00025'
  currentMap['name'] = 'functions'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033')

  # Attribute MolSystem.guid
  contentMap['guid'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-09-14-18:48:26_00002')

  # Attribute MolSystem.hasChemExchange
  currentMap = {}
  contentMap['hasChemExchange'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:31_00022'] = currentMap
  loadMaps['MOLS.MolSystem.hasChemExchange'] = currentMap
  currentMap['tag'] = 'MOLS.MolSystem.hasChemExchange'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:31_00022'
  currentMap['name'] = 'hasChemExchange'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00028')

  # Attribute MolSystem.isModifiable
  contentMap['isModifiable'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-17-14:16:26_00010__www.ccpn.ac.uk_Fogh_2007-10-03-14:53:27_00001__www.ccpn.ac.uk_Fogh_2006-09-14-16:28:57_00002')

  # Attribute MolSystem.keywords
  currentMap = {}
  contentMap['keywords'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:31_00024'] = currentMap
  loadMaps['MOLS.MolSystem.keywords'] = currentMap
  currentMap['tag'] = 'MOLS.MolSystem.keywords'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:31_00024'
  currentMap['name'] = 'keywords'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033')

  # Attribute MolSystem.lastUnlockedBy
  contentMap['lastUnlockedBy'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-12-31-09:00:59_00003__www.ccpn.ac.uk_Fogh_2007-10-03-14:53:27_00001__www.ccpn.ac.uk_Fogh_2006-09-14-16:28:57_00002')

  # Attribute MolSystem.name
  currentMap = {}
  contentMap['name'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:31_00020'] = currentMap
  loadMaps['MOLS.MolSystem.name'] = currentMap
  currentMap['tag'] = 'MOLS.MolSystem.name'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:31_00020'
  currentMap['name'] = 'name'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['proc'] = 'direct'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00035')

  # Role MolSystem.chainGroups
  currentMap = {}
  contentMap['chainGroups'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2016-09-12-10:13:31_00005'] = currentMap
  loadMaps['MOLS.MolSystem.chainGroups'] = currentMap
  currentMap['tag'] = 'MOLS.MolSystem.chainGroups'
  currentMap['type'] = 'child'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2016-09-12-10:13:31_00005'
  currentMap['name'] = 'chainGroups'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['implSkip'] = True
  currentMap['content'] = globalMap.get('MOLS').get('abstractTypes')

  # Role MolSystem.chainInteractions
  currentMap = {}
  contentMap['chainInteractions'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:31_00004'] = currentMap
  loadMaps['MOLS.MolSystem.chainInteractions'] = currentMap
  currentMap['tag'] = 'MOLS.MolSystem.chainInteractions'
  currentMap['type'] = 'child'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:31_00004'
  currentMap['name'] = 'chainInteractions'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['implSkip'] = True
  currentMap['content'] = globalMap.get('MOLS').get('abstractTypes')

  # Role MolSystem.chains
  currentMap = {}
  contentMap['chains'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:31_00002'] = currentMap
  loadMaps['MOLS.MolSystem.chains'] = currentMap
  currentMap['tag'] = 'MOLS.MolSystem.chains'
  currentMap['type'] = 'child'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:31_00002'
  currentMap['name'] = 'chains'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['implSkip'] = True
  currentMap['content'] = globalMap.get('MOLS').get('abstractTypes')

  # Role MolSystem.citations
  currentMap = {}
  contentMap['citations'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:31_00010'] = currentMap
  loadMaps['MOLS.MolSystem.citations'] = currentMap
  currentMap['tag'] = 'MOLS.MolSystem.citations'
  currentMap['type'] = 'exolink'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:31_00010'
  currentMap['name'] = 'citations'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['implSkip'] = True
  currentMap['copyOverride'] = True
  currentMap['content'] = globalMap.get('CITA').get('exolinks')

  # Role MolSystem.dbReferences
  currentMap = {}
  contentMap['dbReferences'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2007-11-06-17:36:17_00007'] = currentMap
  loadMaps['MOLS.MolSystem.dbReferences'] = currentMap
  currentMap['tag'] = 'MOLS.MolSystem.dbReferences'
  currentMap['type'] = 'exolink'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2007-11-06-17:36:17_00007'
  currentMap['name'] = 'dbReferences'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['implSkip'] = True
  currentMap['copyOverride'] = True
  currentMap['content'] = globalMap.get('DBR').get('exolinks')

  # Role MolSystem.genericBonds
  currentMap = {}
  contentMap['genericBonds'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:31_00018'] = currentMap
  loadMaps['MOLS.MolSystem.genericBonds'] = currentMap
  currentMap['tag'] = 'MOLS.MolSystem.genericBonds'
  currentMap['type'] = 'child'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:31_00018'
  currentMap['name'] = 'genericBonds'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['implSkip'] = True
  currentMap['content'] = globalMap.get('MOLS').get('abstractTypes')

  # Role MolSystem.molSystemLinks
  currentMap = {}
  contentMap['molSystemLinks'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:31_00008'] = currentMap
  loadMaps['MOLS.MolSystem.molSystemLinks'] = currentMap
  currentMap['tag'] = 'MOLS.MolSystem.molSystemLinks'
  currentMap['type'] = 'child'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:31_00008'
  currentMap['name'] = 'molSystemLinks'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['implSkip'] = True
  currentMap['content'] = globalMap.get('MOLS').get('abstractTypes')

  # Role MolSystem.molSystemSysNames
  currentMap = {}
  contentMap['molSystemSysNames'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:31_00006'] = currentMap
  loadMaps['MOLS.MolSystem.molSystemSysNames'] = currentMap
  currentMap['tag'] = 'MOLS.MolSystem.molSystemSysNames'
  currentMap['type'] = 'child'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:31_00006'
  currentMap['name'] = 'molSystemSysNames'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['implSkip'] = True
  currentMap['content'] = globalMap.get('MOLS').get('abstractTypes')

  # Role MolSystem.structureGroups
  currentMap = {}
  contentMap['structureGroups'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:31_00014'] = currentMap
  loadMaps['MOLS.MolSystem.structureGroups'] = currentMap
  currentMap['tag'] = 'MOLS.MolSystem.structureGroups'
  currentMap['type'] = 'child'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:31_00014'
  currentMap['name'] = 'structureGroups'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['implSkip'] = True
  currentMap['content'] = globalMap.get('MOLS').get('abstractTypes')
  # End of MolSystem

  currentMap = abstractTypes.get('MolSystem')
  aList = ['_ID', '_lastId', 'code', 'createdBy', 'guid', 'hasChemExchange', 'isModifiable', 'lastUnlockedBy']
  currentMap['headerAttrs'] = aList
  aList = ['ccpnInternalData', 'commonNames', 'details', 'functions', 'keywords', 'name']
  currentMap['simpleAttrs'] = aList
  aList = ['structureGroups', 'molSystemSysNames', 'molSystemLinks', 'genericBonds', 'chains', 'chainInteractions', 'chainGroups', 'dbReferences', 'citations', 'applicationData']
  currentMap['cplxAttrs'] = aList
  aList = ['chainGroups', 'chainInteractions', 'chains', 'genericBonds', 'molSystemLinks', 'molSystemSysNames', 'structureGroups']
  currentMap['children'] = aList

  # Class MolSystemLink
  currentMap = {}
  abstractTypes['MolSystemLink'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-14:22:54_00027'] = currentMap
  loadMaps['MOLS.MolSystemLink'] = currentMap
  currentMap['tag'] = 'MOLS.MolSystemLink'
  currentMap['type'] = 'class'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-14:22:54_00027'
  currentMap['eType'] = 'cplx'
  currentMap['fromParent'] = 'molSystemLinks'
  currentMap['class'] = ccpnmodel.ccpncore.api.ccp.molecule.MolSystem.MolSystemLink
  contentMap = {}
  currentMap['content'] = contentMap

  # Attribute MolSystemLink._ID
  contentMap['_ID'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2014-03-03-16:24:15_00001')

  # Attribute MolSystemLink.applicationData
  contentMap['applicationData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-09-14-18:48:27_00007')

  # Attribute MolSystemLink.ccpnInternalData
  contentMap['ccpnInternalData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2016-06-28-10:49:27_00001')

  # Attribute MolSystemLink.dihedralAngle
  currentMap = {}
  contentMap['dihedralAngle'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:32_00025'] = currentMap
  loadMaps['MOLS.MolSystemLink.dihedralAngle'] = currentMap
  currentMap['tag'] = 'MOLS.MolSystemLink.dihedralAngle'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:32_00025'
  currentMap['name'] = 'dihedralAngle'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:54_00050')

  # Role MolSystemLink.molSystemLinkEnds
  currentMap = {}
  contentMap['molSystemLinkEnds'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:33_00031'] = currentMap
  loadMaps['MOLS.MolSystemLink.molSystemLinkEnds'] = currentMap
  currentMap['tag'] = 'MOLS.MolSystemLink.molSystemLinkEnds'
  currentMap['type'] = 'link'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:33_00031'
  currentMap['name'] = 'molSystemLinkEnds'
  currentMap['hicard'] = 2
  currentMap['locard'] = 2
  currentMap['copyOverride'] = False
  # End of MolSystemLink

  currentMap = abstractTypes.get('MolSystemLink')
  aList = ['_ID', 'dihedralAngle']
  currentMap['headerAttrs'] = aList
  aList = ['ccpnInternalData', 'molSystemLinkEnds']
  currentMap['simpleAttrs'] = aList
  aList = ['applicationData']
  currentMap['cplxAttrs'] = aList

  # Class MolSystemLinkEnd
  currentMap = {}
  abstractTypes['MolSystemLinkEnd'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-14:22:54_00034'] = currentMap
  loadMaps['MOLS.MolSystemLinkEnd'] = currentMap
  currentMap['tag'] = 'MOLS.MolSystemLinkEnd'
  currentMap['type'] = 'class'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-14:22:54_00034'
  currentMap['eType'] = 'cplx'
  currentMap['fromParent'] = 'molSystemLinkEnds'
  currentMap['objkey'] = 'linkCode'
  currentMap['class'] = ccpnmodel.ccpncore.api.ccp.molecule.MolSystem.MolSystemLinkEnd
  contentMap = {}
  currentMap['content'] = contentMap

  # Attribute MolSystemLinkEnd._ID
  contentMap['_ID'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2014-03-03-16:24:15_00001')

  # Attribute MolSystemLinkEnd.applicationData
  contentMap['applicationData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-09-14-18:48:27_00007')

  # Attribute MolSystemLinkEnd.ccpnInternalData
  contentMap['ccpnInternalData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2016-06-28-10:49:27_00001')

  # Attribute MolSystemLinkEnd.linkCode
  currentMap = {}
  contentMap['linkCode'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:33_00034'] = currentMap
  loadMaps['MOLS.MolSystemLinkEnd.linkCode'] = currentMap
  currentMap['tag'] = 'MOLS.MolSystemLinkEnd.linkCode'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:33_00034'
  currentMap['name'] = 'linkCode'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00037')

  # Role MolSystemLinkEnd.molSystemLink
  currentMap = {}
  contentMap['molSystemLink'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:33_00032'] = currentMap
  loadMaps['MOLS.MolSystemLinkEnd.molSystemLink'] = currentMap
  currentMap['tag'] = 'MOLS.MolSystemLinkEnd.molSystemLink'
  currentMap['type'] = 'link'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:33_00032'
  currentMap['name'] = 'molSystemLink'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['copyOverride'] = False
  # End of MolSystemLinkEnd

  currentMap = abstractTypes.get('MolSystemLinkEnd')
  aList = ['_ID', 'linkCode']
  currentMap['headerAttrs'] = aList
  aList = ['ccpnInternalData']
  currentMap['simpleAttrs'] = aList
  aList = ['molSystemLink']
  currentMap['optLinks'] = aList
  aList = ['applicationData']
  currentMap['cplxAttrs'] = aList

  # Class MolSystemSysName
  currentMap = {}
  abstractTypes['MolSystemSysName'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-14:22:54_00028'] = currentMap
  loadMaps['MOLS.MolSystemSysName'] = currentMap
  currentMap['tag'] = 'MOLS.MolSystemSysName'
  currentMap['type'] = 'class'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-14:22:54_00028'
  currentMap['eType'] = 'cplx'
  currentMap['fromParent'] = 'molSystemSysNames'
  currentMap['objkey'] = 'namingSystem'
  currentMap['class'] = ccpnmodel.ccpncore.api.ccp.molecule.MolSystem.MolSystemSysName
  contentMap = {}
  currentMap['content'] = contentMap

  # Attribute MolSystemSysName._ID
  contentMap['_ID'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2014-03-03-16:24:15_00001')

  # Attribute MolSystemSysName.applicationData
  contentMap['applicationData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-09-14-18:48:27_00007')

  # Attribute MolSystemSysName.ccpnInternalData
  contentMap['ccpnInternalData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2016-06-28-10:49:27_00001')

  # Attribute MolSystemSysName.name
  currentMap = {}
  contentMap['name'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:32_00027'] = currentMap
  loadMaps['MOLS.MolSystemSysName.name'] = currentMap
  currentMap['tag'] = 'MOLS.MolSystemSysName.name'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:32_00027'
  currentMap['name'] = 'name'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033')

  # Attribute MolSystemSysName.namingSystem
  currentMap = {}
  contentMap['namingSystem'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:32_00026'] = currentMap
  loadMaps['MOLS.MolSystemSysName.namingSystem'] = currentMap
  currentMap['tag'] = 'MOLS.MolSystemSysName.namingSystem'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:32_00026'
  currentMap['name'] = 'namingSystem'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00037')
  # End of MolSystemSysName

  currentMap = abstractTypes.get('MolSystemSysName')
  aList = ['_ID', 'namingSystem']
  currentMap['headerAttrs'] = aList
  aList = ['ccpnInternalData', 'name']
  currentMap['simpleAttrs'] = aList
  aList = ['applicationData']
  currentMap['cplxAttrs'] = aList

  # Class Residue
  currentMap = {}
  abstractTypes['Residue'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-14:22:54_00030'] = currentMap
  loadMaps['MOLS.Residue'] = currentMap
  currentMap['tag'] = 'MOLS.Residue'
  currentMap['type'] = 'class'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-14:22:54_00030'
  currentMap['eType'] = 'cplx'
  currentMap['fromParent'] = 'residues'
  currentMap['objkey'] = 'seqId'
  currentMap['class'] = ccpnmodel.ccpncore.api.ccp.molecule.MolSystem.Residue
  contentMap = {}
  currentMap['content'] = contentMap

  # Attribute Residue._ID
  contentMap['_ID'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2014-03-03-16:24:15_00001')

  # Attribute Residue.applicationData
  contentMap['applicationData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-09-14-18:48:27_00007')

  # Attribute Residue.ccpnInternalData
  contentMap['ccpnInternalData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2016-06-28-10:49:27_00001')

  # Attribute Residue.descriptor
  currentMap = {}
  contentMap['descriptor'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:33_00007'] = currentMap
  loadMaps['MOLS.Residue.descriptor'] = currentMap
  currentMap['tag'] = 'MOLS.Residue.descriptor'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:33_00007'
  currentMap['name'] = 'descriptor'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033')

  # Attribute Residue.details
  currentMap = {}
  contentMap['details'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:33_00008'] = currentMap
  loadMaps['MOLS.Residue.details'] = currentMap
  currentMap['tag'] = 'MOLS.Residue.details'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:33_00008'
  currentMap['name'] = 'details'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['proc'] = 'direct'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00035')

  # Attribute Residue.linking
  currentMap = {}
  contentMap['linking'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:33_00006'] = currentMap
  loadMaps['MOLS.Residue.linking'] = currentMap
  currentMap['tag'] = 'MOLS.Residue.linking'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:33_00006'
  currentMap['name'] = 'linking'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:52_00025')

  # Attribute Residue.seqCode
  currentMap = {}
  contentMap['seqCode'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:33_00001'] = currentMap
  loadMaps['MOLS.Residue.seqCode'] = currentMap
  currentMap['tag'] = 'MOLS.Residue.seqCode'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:33_00001'
  currentMap['name'] = 'seqCode'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['proc'] = 'direct'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00032')

  # Attribute Residue.seqId
  currentMap = {}
  contentMap['seqId'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:32_00043'] = currentMap
  loadMaps['MOLS.Residue.seqId'] = currentMap
  currentMap['tag'] = 'MOLS.Residue.seqId'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:32_00043'
  currentMap['name'] = 'seqId'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['proc'] = 'direct'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00032')

  # Attribute Residue.seqInsertCode
  currentMap = {}
  contentMap['seqInsertCode'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:33_00002'] = currentMap
  loadMaps['MOLS.Residue.seqInsertCode'] = currentMap
  currentMap['tag'] = 'MOLS.Residue.seqInsertCode'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:33_00002'
  currentMap['name'] = 'seqInsertCode'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['eType'] = 'cplx'
  currentMap['default'] = ' '
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033')

  # Role Residue.atoms
  currentMap = {}
  contentMap['atoms'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:32_00033'] = currentMap
  loadMaps['MOLS.Residue.atoms'] = currentMap
  currentMap['tag'] = 'MOLS.Residue.atoms'
  currentMap['type'] = 'child'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:32_00033'
  currentMap['name'] = 'atoms'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['content'] = globalMap.get('MOLS').get('abstractTypes')

  # Role Residue.chainFragment
  currentMap = {}
  contentMap['chainFragment'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:33_00037'] = currentMap
  loadMaps['MOLS.Residue.chainFragment'] = currentMap
  currentMap['tag'] = 'MOLS.Residue.chainFragment'
  currentMap['type'] = 'link'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:33_00037'
  currentMap['name'] = 'chainFragment'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['copyOverride'] = False

  # Role Residue.molSystemLinkEnds
  currentMap = {}
  contentMap['molSystemLinkEnds'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:32_00042'] = currentMap
  loadMaps['MOLS.Residue.molSystemLinkEnds'] = currentMap
  currentMap['tag'] = 'MOLS.Residue.molSystemLinkEnds'
  currentMap['type'] = 'child'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:32_00042'
  currentMap['name'] = 'molSystemLinkEnds'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['content'] = globalMap.get('MOLS').get('abstractTypes')
  # End of Residue

  currentMap = abstractTypes.get('Residue')
  aList = ['_ID', 'linking', 'seqCode', 'seqId']
  currentMap['headerAttrs'] = aList
  aList = ['ccpnInternalData', 'descriptor', 'details', 'seqInsertCode']
  currentMap['simpleAttrs'] = aList
  aList = ['chainFragment']
  currentMap['optLinks'] = aList
  aList = ['molSystemLinkEnds', 'atoms', 'applicationData']
  currentMap['cplxAttrs'] = aList
  aList = ['atoms', 'molSystemLinkEnds']
  currentMap['children'] = aList

  # Class StructureGroup
  currentMap = {}
  abstractTypes['StructureGroup'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-14:22:54_00033'] = currentMap
  loadMaps['MOLS.StructureGroup'] = currentMap
  currentMap['tag'] = 'MOLS.StructureGroup'
  currentMap['type'] = 'class'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-14:22:54_00033'
  currentMap['eType'] = 'cplx'
  currentMap['fromParent'] = 'structureGroups'
  currentMap['objkey'] = 'serial'
  currentMap['class'] = ccpnmodel.ccpncore.api.ccp.molecule.MolSystem.StructureGroup
  contentMap = {}
  currentMap['content'] = contentMap

  # Attribute StructureGroup._ID
  contentMap['_ID'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2014-03-03-16:24:15_00001')

  # Attribute StructureGroup.applicationData
  contentMap['applicationData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-09-14-18:48:27_00007')

  # Attribute StructureGroup.ccpnInternalData
  contentMap['ccpnInternalData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2016-06-28-10:49:27_00001')

  # Attribute StructureGroup.details
  currentMap = {}
  contentMap['details'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:33_00030'] = currentMap
  loadMaps['MOLS.StructureGroup.details'] = currentMap
  currentMap['tag'] = 'MOLS.StructureGroup.details'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:33_00030'
  currentMap['name'] = 'details'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['proc'] = 'direct'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00035')

  # Attribute StructureGroup.name
  currentMap = {}
  contentMap['name'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:33_00028'] = currentMap
  loadMaps['MOLS.StructureGroup.name'] = currentMap
  currentMap['tag'] = 'MOLS.StructureGroup.name'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:33_00028'
  currentMap['name'] = 'name'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033')

  # Attribute StructureGroup.serial
  currentMap = {}
  contentMap['serial'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:23:33_00027'] = currentMap
  loadMaps['MOLS.StructureGroup.serial'] = currentMap
  currentMap['tag'] = 'MOLS.StructureGroup.serial'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:23:33_00027'
  currentMap['name'] = 'serial'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00032')
  # End of StructureGroup

  currentMap = abstractTypes.get('StructureGroup')
  aList = ['_ID', 'serial']
  currentMap['headerAttrs'] = aList
  aList = ['ccpnInternalData', 'details', 'name']
  currentMap['simpleAttrs'] = aList
  aList = ['applicationData']
  currentMap['cplxAttrs'] = aList

  # Out-of-package link to Atom
  currentMap = {}
  exolinks['Atom'] = currentMap
  loadMaps['MOLS.exo-Atom'] = currentMap
  currentMap['tag'] = 'MOLS.exo-Atom'
  currentMap['type'] = 'exo'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-14:22:54_00029'
  currentMap['name'] = 'Atom'
  currentMap['eType'] = 'cplx'
  currentMap['class'] = ccpnmodel.ccpncore.api.ccp.molecule.MolSystem.Atom
  aList = list()
  currentMap['keyMaps'] = aList
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2008-06-30-16:30:50_00001'))
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033'))
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00032'))
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00037'))

  # Out-of-package link to Chain
  currentMap = {}
  exolinks['Chain'] = currentMap
  loadMaps['MOLS.exo-Chain'] = currentMap
  currentMap['tag'] = 'MOLS.exo-Chain'
  currentMap['type'] = 'exo'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-14:22:54_00024'
  currentMap['name'] = 'Chain'
  currentMap['eType'] = 'cplx'
  currentMap['class'] = ccpnmodel.ccpncore.api.ccp.molecule.MolSystem.Chain
  aList = list()
  currentMap['keyMaps'] = aList
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2008-06-30-16:30:50_00001'))
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033'))

  # Out-of-package link to ChainFragment
  currentMap = {}
  exolinks['ChainFragment'] = currentMap
  loadMaps['MOLS.exo-ChainFragment'] = currentMap
  currentMap['tag'] = 'MOLS.exo-ChainFragment'
  currentMap['type'] = 'exo'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-14:22:54_00036'
  currentMap['name'] = 'ChainFragment'
  currentMap['eType'] = 'cplx'
  currentMap['class'] = ccpnmodel.ccpncore.api.ccp.molecule.MolSystem.ChainFragment
  aList = list()
  currentMap['keyMaps'] = aList
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2008-06-30-16:30:50_00001'))
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033'))
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00032'))

  # Out-of-package link to ChainGroup
  currentMap = {}
  exolinks['ChainGroup'] = currentMap
  loadMaps['MOLS.exo-ChainGroup'] = currentMap
  currentMap['tag'] = 'MOLS.exo-ChainGroup'
  currentMap['type'] = 'exo'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2016-09-12-10:13:24_00001'
  currentMap['name'] = 'ChainGroup'
  currentMap['eType'] = 'cplx'
  currentMap['class'] = ccpnmodel.ccpncore.api.ccp.molecule.MolSystem.ChainGroup
  aList = list()
  currentMap['keyMaps'] = aList
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2008-06-30-16:30:50_00001'))
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033'))

  # Out-of-package link to ChainInteraction
  currentMap = {}
  exolinks['ChainInteraction'] = currentMap
  loadMaps['MOLS.exo-ChainInteraction'] = currentMap
  currentMap['tag'] = 'MOLS.exo-ChainInteraction'
  currentMap['type'] = 'exo'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-14:22:54_00026'
  currentMap['name'] = 'ChainInteraction'
  currentMap['eType'] = 'cplx'
  currentMap['class'] = ccpnmodel.ccpncore.api.ccp.molecule.MolSystem.ChainInteraction
  aList = list()
  currentMap['keyMaps'] = aList
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2008-06-30-16:30:50_00001'))
  aList.append(globalMap.get('MOLS').get('exolinks'))
  aList.append(globalMap.get('MOLS').get('exolinks'))

  # Out-of-package link to GenericBond
  currentMap = {}
  exolinks['GenericBond'] = currentMap
  loadMaps['MOLS.exo-GenericBond'] = currentMap
  currentMap['tag'] = 'MOLS.exo-GenericBond'
  currentMap['type'] = 'exo'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-14:22:54_00037'
  currentMap['name'] = 'GenericBond'
  currentMap['eType'] = 'cplx'
  currentMap['class'] = ccpnmodel.ccpncore.api.ccp.molecule.MolSystem.GenericBond
  aList = list()
  currentMap['keyMaps'] = aList
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2008-06-30-16:30:50_00001'))
  aList.append(globalMap.get('MOLS').get('exolinks'))
  aList.append(globalMap.get('MOLS').get('exolinks'))

  # Out-of-package link to MolSystem
  currentMap = {}
  exolinks['MolSystem'] = currentMap
  loadMaps['MOLS.exo-MolSystem'] = currentMap
  currentMap['tag'] = 'MOLS.exo-MolSystem'
  currentMap['type'] = 'exo'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-14:22:54_00023'
  currentMap['name'] = 'MolSystem'
  currentMap['eType'] = 'cplx'
  currentMap['class'] = ccpnmodel.ccpncore.api.ccp.molecule.MolSystem.MolSystem
  aList = list()
  currentMap['keyMaps'] = aList
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2008-06-30-16:30:50_00001'))

  # Out-of-package link to MolSystemLink
  currentMap = {}
  exolinks['MolSystemLink'] = currentMap
  loadMaps['MOLS.exo-MolSystemLink'] = currentMap
  currentMap['tag'] = 'MOLS.exo-MolSystemLink'
  currentMap['type'] = 'exo'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-14:22:54_00027'
  currentMap['name'] = 'MolSystemLink'
  currentMap['eType'] = 'cplx'
  currentMap['class'] = ccpnmodel.ccpncore.api.ccp.molecule.MolSystem.MolSystemLink
  aList = list()
  currentMap['keyMaps'] = aList
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2008-06-30-16:30:50_00001'))
  aList.append(globalMap.get('MOLS').get('exolinks'))
  aList.append(globalMap.get('MOLS').get('exolinks'))

  # Out-of-package link to MolSystemLinkEnd
  currentMap = {}
  exolinks['MolSystemLinkEnd'] = currentMap
  loadMaps['MOLS.exo-MolSystemLinkEnd'] = currentMap
  currentMap['tag'] = 'MOLS.exo-MolSystemLinkEnd'
  currentMap['type'] = 'exo'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-14:22:54_00034'
  currentMap['name'] = 'MolSystemLinkEnd'
  currentMap['eType'] = 'cplx'
  currentMap['class'] = ccpnmodel.ccpncore.api.ccp.molecule.MolSystem.MolSystemLinkEnd
  aList = list()
  currentMap['keyMaps'] = aList
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2008-06-30-16:30:50_00001'))
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033'))
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00032'))
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00037'))

  # Out-of-package link to MolSystemSysName
  currentMap = {}
  exolinks['MolSystemSysName'] = currentMap
  loadMaps['MOLS.exo-MolSystemSysName'] = currentMap
  currentMap['tag'] = 'MOLS.exo-MolSystemSysName'
  currentMap['type'] = 'exo'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-14:22:54_00028'
  currentMap['name'] = 'MolSystemSysName'
  currentMap['eType'] = 'cplx'
  currentMap['class'] = ccpnmodel.ccpncore.api.ccp.molecule.MolSystem.MolSystemSysName
  aList = list()
  currentMap['keyMaps'] = aList
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2008-06-30-16:30:50_00001'))
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00037'))

  # Out-of-package link to Residue
  currentMap = {}
  exolinks['Residue'] = currentMap
  loadMaps['MOLS.exo-Residue'] = currentMap
  currentMap['tag'] = 'MOLS.exo-Residue'
  currentMap['type'] = 'exo'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-14:22:54_00030'
  currentMap['name'] = 'Residue'
  currentMap['eType'] = 'cplx'
  currentMap['class'] = ccpnmodel.ccpncore.api.ccp.molecule.MolSystem.Residue
  aList = list()
  currentMap['keyMaps'] = aList
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2008-06-30-16:30:50_00001'))
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033'))
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00032'))

  # Out-of-package link to StructureGroup
  currentMap = {}
  exolinks['StructureGroup'] = currentMap
  loadMaps['MOLS.exo-StructureGroup'] = currentMap
  currentMap['tag'] = 'MOLS.exo-StructureGroup'
  currentMap['type'] = 'exo'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-14:22:54_00033'
  currentMap['name'] = 'StructureGroup'
  currentMap['eType'] = 'cplx'
  currentMap['class'] = ccpnmodel.ccpncore.api.ccp.molecule.MolSystem.StructureGroup
  aList = list()
  currentMap['keyMaps'] = aList
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2008-06-30-16:30:50_00001'))
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00032'))
