"""
#######################################################################

CCPN Data Model version 3.0.2

Autogenerated by PyXmlMapWrite on Wed Jun 22 15:48:16 2016
  from data model element ccp.lims.Sample

#######################################################################
======================COPYRIGHT/LICENSE START==========================

Sample.py: python XML-I/O-mapping for CCPN data model, MetaPackage ccp.lims.Sample

Copyright (C) 2007  (CCPN Project)

=======================================================================

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

A copy of this license can be found in ../../../../../../../license/LGPL.license

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA


======================COPYRIGHT/LICENSE END============================

for further information, please contact :

- CCPN website (http://www.ccpn.ac.uk/)

- email: ccpn@bioc.cam.ac.uk

=======================================================================

If you are using this software for academic purposes, we suggest
quoting the following references:

===========================REFERENCE START=============================
Rasmus H. Fogh, Wayne Boucher, Wim F. Vranken, Anne
Pajon, Tim J. Stevens, T.N. Bhat, John Westbrook, John M.C. Ionides and
Ernest D. Laue (2005). A framework for scientific data modeling and automated
software development. Bioinformatics 21, 1678-1684.


This file was generated with the Memops software generation framework,
and contains original contributions embedded in the framework

===========================REFERENCE END===============================
"""

from ccpnmodel.ccpncore.memops.metamodel.Constants import baseDataTypeModule as basicDataTypes
NaN = float('NaN')
# 
#  Current package api
import ccpnmodel.ccpncore.api.ccp.lims.Sample

def makeMapping(globalMap):
  """
  generates XML I/O mapping for package SAM, adding it to globalMap
  """
  
  from ccpnmodel.ccpncore.xml.memops.Implementation import bool2str, str2bool

  # Set up top level dictionaries
  loadMaps = globalMap.get('loadMaps')
  mapsByGuid = globalMap.get('mapsByGuid')

  abstractTypes = globalMap.get('SAM').get('abstractTypes')
  exolinks = globalMap.get('SAM').get('exolinks')

  # DataType AmountUnit
  currentMap = {}
  abstractTypes['AmountUnit'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-14:22:44_00006'] = currentMap
  loadMaps['SAM.AmountUnit'] = currentMap
  currentMap['tag'] = 'SAM.AmountUnit'
  currentMap['type'] = 'simple'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-14:22:44_00006'
  currentMap['toStr'] = 'text'
  currentMap['cnvrt'] = 'text'

  # DataType ConcentrationUnit
  currentMap = {}
  abstractTypes['ConcentrationUnit'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-14:22:44_00005'] = currentMap
  loadMaps['SAM.ConcentrationUnit'] = currentMap
  currentMap['tag'] = 'SAM.ConcentrationUnit'
  currentMap['type'] = 'simple'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-14:22:44_00005'
  currentMap['toStr'] = 'text'
  currentMap['cnvrt'] = 'text'

  # Class AbstractSample
  currentMap = {}
  abstractTypes['AbstractSample'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-14:22:44_00007'] = currentMap
  currentMap['type'] = 'class'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-14:22:44_00007'
  currentMap['eType'] = 'cplx'
  currentMap['fromParent'] = 'samples'
  currentMap['objkey'] = 'name'
  currentMap['class'] = ccpnmodel.ccpncore.api.ccp.lims.Sample.AbstractSample
  contentMap = {}
  currentMap['content'] = contentMap

  # Attribute AbstractSample._ID
  contentMap['_ID'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2014-03-03-16:24:15_00001')

  # Attribute AbstractSample.applicationData
  contentMap['applicationData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-09-14-18:48:27_00007')

  # Attribute AbstractSample.details
  currentMap = {}
  contentMap['details'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:22:46_00009'] = currentMap
  loadMaps['SAM.AbstractSample.details'] = currentMap
  currentMap['tag'] = 'SAM.AbstractSample.details'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:22:46_00009'
  currentMap['name'] = 'details'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['proc'] = 'direct'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00035')

  # Attribute AbstractSample.ionicStrength
  currentMap = {}
  contentMap['ionicStrength'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:22:46_00006'] = currentMap
  loadMaps['SAM.AbstractSample.ionicStrength'] = currentMap
  currentMap['tag'] = 'SAM.AbstractSample.ionicStrength'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:22:46_00006'
  currentMap['name'] = 'ionicStrength'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00031')

  # Attribute AbstractSample.isHazardous
  currentMap = {}
  contentMap['isHazardous'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:22:46_00007'] = currentMap
  loadMaps['SAM.AbstractSample.isHazardous'] = currentMap
  currentMap['tag'] = 'SAM.AbstractSample.isHazardous'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:22:46_00007'
  currentMap['name'] = 'isHazardous'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00028')

  # Attribute AbstractSample.isVirtual
  currentMap = {}
  contentMap['isVirtual'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2015-09-22-16:45:30_00003'] = currentMap
  loadMaps['SAM.AbstractSample.isVirtual'] = currentMap
  currentMap['tag'] = 'SAM.AbstractSample.isVirtual'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2015-09-22-16:45:30_00003'
  currentMap['name'] = 'isVirtual'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['default'] = False
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00028')

  # Attribute AbstractSample.name
  currentMap = {}
  contentMap['name'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:22:46_00004'] = currentMap
  loadMaps['SAM.AbstractSample.name'] = currentMap
  currentMap['tag'] = 'SAM.AbstractSample.name'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:22:46_00004'
  currentMap['name'] = 'name'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033')

  # Attribute AbstractSample.ph
  currentMap = {}
  contentMap['ph'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:22:46_00005'] = currentMap
  loadMaps['SAM.AbstractSample.ph'] = currentMap
  currentMap['tag'] = 'SAM.AbstractSample.ph'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:22:46_00005'
  currentMap['name'] = 'ph'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00031')

  # Role AbstractSample.sampleComponents
  currentMap = {}
  contentMap['sampleComponents'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:22:46_00001'] = currentMap
  loadMaps['SAM.AbstractSample.sampleComponents'] = currentMap
  currentMap['tag'] = 'SAM.AbstractSample.sampleComponents'
  currentMap['type'] = 'child'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:22:46_00001'
  currentMap['name'] = 'sampleComponents'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['content'] = globalMap.get('SAM').get('abstractTypes')
  # End of AbstractSample

  currentMap = abstractTypes.get('AbstractSample')
  aList = ['_ID', 'ionicStrength', 'isHazardous', 'isVirtual', 'ph']
  currentMap['headerAttrs'] = aList
  aList = ['details', 'name']
  currentMap['simpleAttrs'] = aList
  aList = ['sampleComponents', 'applicationData']
  currentMap['cplxAttrs'] = aList
  aList = ['sampleComponents']
  currentMap['children'] = aList

  # Class SampleComponent
  currentMap = {}
  abstractTypes['SampleComponent'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-14:22:44_00002'] = currentMap
  loadMaps['SAM.SampleComponent'] = currentMap
  currentMap['tag'] = 'SAM.SampleComponent'
  currentMap['type'] = 'class'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-14:22:44_00002'
  currentMap['eType'] = 'cplx'
  currentMap['fromParent'] = 'sampleComponents'
  currentMap['class'] = ccpnmodel.ccpncore.api.ccp.lims.Sample.SampleComponent
  contentMap = {}
  currentMap['content'] = contentMap

  # Attribute SampleComponent._ID
  contentMap['_ID'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2014-03-03-16:24:15_00001')

  # Attribute SampleComponent.applicationData
  contentMap['applicationData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-09-14-18:48:27_00007')

  # Attribute SampleComponent.chainCodes
  currentMap = {}
  contentMap['chainCodes'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2015-08-14-16:14:51_00001'] = currentMap
  loadMaps['SAM.SampleComponent.chainCodes'] = currentMap
  currentMap['tag'] = 'SAM.SampleComponent.chainCodes'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2015-08-14-16:14:51_00001'
  currentMap['name'] = 'chainCodes'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00037')

  # Attribute SampleComponent.concentration
  currentMap = {}
  contentMap['concentration'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:22:44_00001'] = currentMap
  loadMaps['SAM.SampleComponent.concentration'] = currentMap
  currentMap['tag'] = 'SAM.SampleComponent.concentration'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:22:44_00001'
  currentMap['name'] = 'concentration'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00031')

  # Attribute SampleComponent.concentrationError
  currentMap = {}
  contentMap['concentrationError'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:22:44_00002'] = currentMap
  loadMaps['SAM.SampleComponent.concentrationError'] = currentMap
  currentMap['tag'] = 'SAM.SampleComponent.concentrationError'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:22:44_00002'
  currentMap['name'] = 'concentrationError'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00031')

  # Attribute SampleComponent.concentrationUnit
  currentMap = {}
  contentMap['concentrationUnit'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:22:44_00003'] = currentMap
  loadMaps['SAM.SampleComponent.concentrationUnit'] = currentMap
  currentMap['tag'] = 'SAM.SampleComponent.concentrationUnit'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:22:44_00003'
  currentMap['name'] = 'concentrationUnit'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:44_00005')

  # Attribute SampleComponent.details
  currentMap = {}
  contentMap['details'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:22:44_00006'] = currentMap
  loadMaps['SAM.SampleComponent.details'] = currentMap
  currentMap['tag'] = 'SAM.SampleComponent.details'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:22:44_00006'
  currentMap['name'] = 'details'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['proc'] = 'direct'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00035')

  # Attribute SampleComponent.labeling
  currentMap = {}
  contentMap['labeling'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2015-06-22-18:00:46_00002'] = currentMap
  loadMaps['SAM.SampleComponent.labeling'] = currentMap
  currentMap['tag'] = 'SAM.SampleComponent.labeling'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2015-06-22-18:00:46_00002'
  currentMap['name'] = 'labeling'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['default'] = '_NATURAL_ABUNDANCE'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00037')

  # Attribute SampleComponent.name
  currentMap = {}
  contentMap['name'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2015-06-22-18:00:46_00001'] = currentMap
  loadMaps['SAM.SampleComponent.name'] = currentMap
  currentMap['tag'] = 'SAM.SampleComponent.name'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2015-06-22-18:00:46_00001'
  currentMap['name'] = 'name'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033')

  # Attribute SampleComponent.purity
  currentMap = {}
  contentMap['purity'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:22:44_00005'] = currentMap
  loadMaps['SAM.SampleComponent.purity'] = currentMap
  currentMap['tag'] = 'SAM.SampleComponent.purity'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:22:44_00005'
  currentMap['name'] = 'purity'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00058')

  # Attribute SampleComponent.role
  currentMap = {}
  contentMap['role'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2015-06-22-18:00:46_00003'] = currentMap
  loadMaps['SAM.SampleComponent.role'] = currentMap
  currentMap['tag'] = 'SAM.SampleComponent.role'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2015-06-22-18:00:46_00003'
  currentMap['name'] = 'role'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033')

  # Role SampleComponent.container
  currentMap = {}
  contentMap['container'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:22:42_00004'] = currentMap
  loadMaps['SAM.SampleComponent.container'] = currentMap
  currentMap['tag'] = 'SAM.SampleComponent.container'
  currentMap['type'] = 'link'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:22:42_00004'
  currentMap['name'] = 'container'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['copyOverride'] = True

  # Role SampleComponent.contents
  currentMap = {}
  contentMap['contents'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:22:42_00003'] = currentMap
  loadMaps['SAM.SampleComponent.contents'] = currentMap
  currentMap['tag'] = 'SAM.SampleComponent.contents'
  currentMap['type'] = 'link'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:22:42_00003'
  currentMap['name'] = 'contents'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['copyOverride'] = False

  # Role SampleComponent.refComponent
  currentMap = {}
  contentMap['refComponent'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:22:42_00002'] = currentMap
  loadMaps['SAM.SampleComponent.refComponent'] = currentMap
  currentMap['tag'] = 'SAM.SampleComponent.refComponent'
  currentMap['type'] = 'exolink'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:22:42_00002'
  currentMap['name'] = 'refComponent'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['copyOverride'] = True
  currentMap['content'] = globalMap.get('REFS').get('exolinks')
  # End of SampleComponent

  currentMap = abstractTypes.get('SampleComponent')
  aList = ['_ID', 'concentration', 'concentrationError', 'concentrationUnit', 'labeling', 'purity']
  currentMap['headerAttrs'] = aList
  aList = ['chainCodes', 'details', 'name', 'role', 'contents']
  currentMap['simpleAttrs'] = aList
  aList = ['container']
  currentMap['optLinks'] = aList
  aList = ['applicationData']
  currentMap['cplxAttrs'] = aList

  # Class SampleStore
  currentMap = {}
  abstractTypes['SampleStore'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-09-05-12:37:24_00008'] = currentMap
  loadMaps['SAM.SampleStore'] = currentMap
  currentMap['tag'] = 'SAM.SampleStore'
  currentMap['type'] = 'class'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-09-05-12:37:24_00008'
  currentMap['eType'] = 'cplx'
  currentMap['fromParent'] = 'sampleStores'
  currentMap['isTop'] = True
  currentMap['objkey'] = 'name'
  currentMap['class'] = ccpnmodel.ccpncore.api.ccp.lims.Sample.SampleStore
  contentMap = {}
  currentMap['content'] = contentMap

  # Attribute SampleStore._ID
  contentMap['_ID'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2014-03-03-16:24:15_00001')

  # Attribute SampleStore._lastId
  contentMap['_lastId'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2014-03-05-13:04:27_00001')

  # Attribute SampleStore.applicationData
  contentMap['applicationData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-09-14-18:48:27_00007')

  # Attribute SampleStore.createdBy
  contentMap['createdBy'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-12-31-09:00:59_00002__www.ccpn.ac.uk_Fogh_2007-10-03-14:53:27_00001__www.ccpn.ac.uk_Fogh_2006-09-14-16:28:57_00002')

  # Attribute SampleStore.guid
  contentMap['guid'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-09-14-18:48:26_00002')

  # Attribute SampleStore.isModifiable
  contentMap['isModifiable'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-17-14:16:26_00010__www.ccpn.ac.uk_Fogh_2007-10-03-14:53:27_00001__www.ccpn.ac.uk_Fogh_2006-09-14-16:28:57_00002')

  # Attribute SampleStore.lastUnlockedBy
  contentMap['lastUnlockedBy'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-12-31-09:00:59_00003__www.ccpn.ac.uk_Fogh_2007-10-03-14:53:27_00001__www.ccpn.ac.uk_Fogh_2006-09-14-16:28:57_00002')

  # Attribute SampleStore.name
  currentMap = {}
  contentMap['name'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-09-05-12:37:28_00006'] = currentMap
  loadMaps['SAM.SampleStore.name'] = currentMap
  currentMap['tag'] = 'SAM.SampleStore.name'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-09-05-12:37:28_00006'
  currentMap['name'] = 'name'
  currentMap['hicard'] = 1
  currentMap['locard'] = 1
  currentMap['eType'] = 'cplx'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033')

  # Role SampleStore.refSampleComponentStore
  currentMap = {}
  contentMap['refSampleComponentStore'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2015-06-23-16:34:59_00008'] = currentMap
  loadMaps['SAM.SampleStore.refSampleComponentStore'] = currentMap
  currentMap['tag'] = 'SAM.SampleStore.refSampleComponentStore'
  currentMap['type'] = 'exotop'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2015-06-23-16:34:59_00008'
  currentMap['name'] = 'refSampleComponentStore'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['copyOverride'] = True
  currentMap['content'] = globalMap.get('REFS').get('exolinks')

  # Role SampleStore.samples
  currentMap = {}
  contentMap['samples'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-09-05-12:37:28_00005'] = currentMap
  loadMaps['SAM.SampleStore.samples'] = currentMap
  currentMap['tag'] = 'SAM.SampleStore.samples'
  currentMap['type'] = 'child'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-09-05-12:37:28_00005'
  currentMap['name'] = 'samples'
  currentMap['hicard'] = -1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['implSkip'] = True
  currentMap['content'] = globalMap.get('SAM').get('abstractTypes')
  # End of SampleStore

  currentMap = abstractTypes.get('SampleStore')
  aList = ['_ID', '_lastId', 'createdBy', 'guid', 'isModifiable', 'lastUnlockedBy']
  currentMap['headerAttrs'] = aList
  aList = ['name']
  currentMap['simpleAttrs'] = aList
  aList = ['samples', 'refSampleComponentStore', 'applicationData']
  currentMap['cplxAttrs'] = aList
  aList = ['samples']
  currentMap['children'] = aList

  # Class Sample
  currentMap = {}
  abstractTypes['Sample'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-14:22:44_00001'] = currentMap
  loadMaps['SAM.Sample'] = currentMap
  currentMap['tag'] = 'SAM.Sample'
  currentMap['type'] = 'class'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-14:22:44_00001'
  currentMap['eType'] = 'cplx'
  currentMap['fromParent'] = 'samples'
  currentMap['objkey'] = 'name'
  currentMap['class'] = ccpnmodel.ccpncore.api.ccp.lims.Sample.Sample
  contentMap = {}
  currentMap['content'] = contentMap

  # Attribute Sample._ID
  contentMap['_ID'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2014-03-03-16:24:15_00001')

  # Attribute Sample.amount
  currentMap = {}
  contentMap['amount'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:22:41_00008'] = currentMap
  loadMaps['SAM.Sample.amount'] = currentMap
  currentMap['tag'] = 'SAM.Sample.amount'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:22:41_00008'
  currentMap['name'] = 'amount'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00031')

  # Attribute Sample.amountUnit
  currentMap = {}
  contentMap['amountUnit'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:22:41_00010'] = currentMap
  loadMaps['SAM.Sample.amountUnit'] = currentMap
  currentMap['tag'] = 'SAM.Sample.amountUnit'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:22:41_00010'
  currentMap['name'] = 'amountUnit'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:44_00006')

  # Attribute Sample.applicationData
  contentMap['applicationData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-09-14-18:48:27_00007')

  # Attribute Sample.batchIdentifier
  currentMap = {}
  contentMap['batchIdentifier'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:22:41_00013'] = currentMap
  loadMaps['SAM.Sample.batchIdentifier'] = currentMap
  currentMap['tag'] = 'SAM.Sample.batchIdentifier'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:22:41_00013'
  currentMap['name'] = 'batchIdentifier'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00037')

  # Attribute Sample.colPosition
  currentMap = {}
  contentMap['colPosition'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:22:41_00005'] = currentMap
  loadMaps['SAM.Sample.colPosition'] = currentMap
  currentMap['tag'] = 'SAM.Sample.colPosition'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:22:41_00005'
  currentMap['name'] = 'colPosition'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['proc'] = 'direct'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00032')

  # Attribute Sample.creationDate
  currentMap = {}
  contentMap['creationDate'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:22:41_00007'] = currentMap
  loadMaps['SAM.Sample.creationDate'] = currentMap
  currentMap['tag'] = 'SAM.Sample.creationDate'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:22:41_00007'
  currentMap['name'] = 'creationDate'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['proc'] = 'direct'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00029')

  # Attribute Sample.details
  contentMap['details'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-18:22:46_00009')

  # Attribute Sample.ionicStrength
  contentMap['ionicStrength'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-18:22:46_00006')

  # Attribute Sample.isHazardous
  contentMap['isHazardous'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-18:22:46_00007')

  # Attribute Sample.isVirtual
  contentMap['isVirtual'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2015-09-22-16:45:30_00003')

  # Attribute Sample.name
  contentMap['name'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-18:22:46_00004')

  # Attribute Sample.ph
  contentMap['ph'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-18:22:46_00005')

  # Attribute Sample.plateIdentifier
  currentMap = {}
  contentMap['plateIdentifier'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2015-06-22-10:30:00_00001'] = currentMap
  loadMaps['SAM.Sample.plateIdentifier'] = currentMap
  currentMap['tag'] = 'SAM.Sample.plateIdentifier'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2015-06-22-10:30:00_00001'
  currentMap['name'] = 'plateIdentifier'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00037')

  # Attribute Sample.rowPosition
  currentMap = {}
  contentMap['rowPosition'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:22:41_00004'] = currentMap
  loadMaps['SAM.Sample.rowPosition'] = currentMap
  currentMap['tag'] = 'SAM.Sample.rowPosition'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:22:41_00004'
  currentMap['name'] = 'rowPosition'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['proc'] = 'direct'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00032')

  # Attribute Sample.subPosition
  currentMap = {}
  contentMap['subPosition'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:22:41_00006'] = currentMap
  loadMaps['SAM.Sample.subPosition'] = currentMap
  currentMap['tag'] = 'SAM.Sample.subPosition'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:22:41_00006'
  currentMap['name'] = 'subPosition'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['proc'] = 'direct'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00032')

  # Role Sample.sampleComponents
  contentMap['sampleComponents'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-18:22:46_00001')
  # End of Sample

  currentMap = abstractTypes.get('Sample')
  aList = ['_ID', 'amount', 'amountUnit', 'batchIdentifier', 'colPosition', 'creationDate', 'ionicStrength', 'isHazardous', 'isVirtual', 'ph', 'plateIdentifier', 'rowPosition', 'subPosition']
  currentMap['headerAttrs'] = aList
  aList = ['details', 'name']
  currentMap['simpleAttrs'] = aList
  aList = ['sampleComponents', 'applicationData']
  currentMap['cplxAttrs'] = aList
  aList = ['sampleComponents']
  currentMap['children'] = aList

  # Class CrystalSample
  currentMap = {}
  abstractTypes['CrystalSample'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-14:22:44_00004'] = currentMap
  loadMaps['SAM.CrystalSample'] = currentMap
  currentMap['tag'] = 'SAM.CrystalSample'
  currentMap['type'] = 'class'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-14:22:44_00004'
  currentMap['eType'] = 'cplx'
  currentMap['fromParent'] = 'samples'
  currentMap['objkey'] = 'name'
  currentMap['class'] = ccpnmodel.ccpncore.api.ccp.lims.Sample.CrystalSample
  contentMap = {}
  currentMap['content'] = contentMap

  # Attribute CrystalSample._ID
  contentMap['_ID'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2014-03-03-16:24:15_00001')

  # Attribute CrystalSample.a
  currentMap = {}
  contentMap['a'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:22:44_00018'] = currentMap
  loadMaps['SAM.CrystalSample.a'] = currentMap
  currentMap['tag'] = 'SAM.CrystalSample.a'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:22:44_00018'
  currentMap['name'] = 'a'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00031')

  # Attribute CrystalSample.alpha
  currentMap = {}
  contentMap['alpha'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:22:45_00003'] = currentMap
  loadMaps['SAM.CrystalSample.alpha'] = currentMap
  currentMap['tag'] = 'SAM.CrystalSample.alpha'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:22:45_00003'
  currentMap['name'] = 'alpha'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00031')

  # Attribute CrystalSample.amount
  contentMap['amount'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-18:22:41_00008')

  # Attribute CrystalSample.amountUnit
  contentMap['amountUnit'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-18:22:41_00010')

  # Attribute CrystalSample.applicationData
  contentMap['applicationData'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-09-14-18:48:27_00007')

  # Attribute CrystalSample.b
  currentMap = {}
  contentMap['b'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:22:45_00001'] = currentMap
  loadMaps['SAM.CrystalSample.b'] = currentMap
  currentMap['tag'] = 'SAM.CrystalSample.b'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:22:45_00001'
  currentMap['name'] = 'b'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00031')

  # Attribute CrystalSample.batchIdentifier
  contentMap['batchIdentifier'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-18:22:41_00013')

  # Attribute CrystalSample.beta
  currentMap = {}
  contentMap['beta'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:22:45_00004'] = currentMap
  loadMaps['SAM.CrystalSample.beta'] = currentMap
  currentMap['tag'] = 'SAM.CrystalSample.beta'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:22:45_00004'
  currentMap['name'] = 'beta'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00031')

  # Attribute CrystalSample.c
  currentMap = {}
  contentMap['c'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:22:45_00002'] = currentMap
  loadMaps['SAM.CrystalSample.c'] = currentMap
  currentMap['tag'] = 'SAM.CrystalSample.c'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:22:45_00002'
  currentMap['name'] = 'c'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00031')

  # Attribute CrystalSample.colPosition
  contentMap['colPosition'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-18:22:41_00005')

  # Attribute CrystalSample.colour
  currentMap = {}
  contentMap['colour'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:22:44_00014'] = currentMap
  loadMaps['SAM.CrystalSample.colour'] = currentMap
  currentMap['tag'] = 'SAM.CrystalSample.colour'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:22:44_00014'
  currentMap['name'] = 'colour'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['proc'] = 'direct'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00035')

  # Attribute CrystalSample.creationDate
  contentMap['creationDate'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-18:22:41_00007')

  # Attribute CrystalSample.crystalType
  currentMap = {}
  contentMap['crystalType'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:22:44_00013'] = currentMap
  loadMaps['SAM.CrystalSample.crystalType'] = currentMap
  currentMap['tag'] = 'SAM.CrystalSample.crystalType'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:22:44_00013'
  currentMap['name'] = 'crystalType'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['proc'] = 'direct'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00035')

  # Attribute CrystalSample.details
  contentMap['details'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-18:22:46_00009')

  # Attribute CrystalSample.gamma
  currentMap = {}
  contentMap['gamma'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:22:45_00005'] = currentMap
  loadMaps['SAM.CrystalSample.gamma'] = currentMap
  currentMap['tag'] = 'SAM.CrystalSample.gamma'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:22:45_00005'
  currentMap['name'] = 'gamma'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00031')

  # Attribute CrystalSample.ionicStrength
  contentMap['ionicStrength'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-18:22:46_00006')

  # Attribute CrystalSample.isHazardous
  contentMap['isHazardous'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-18:22:46_00007')

  # Attribute CrystalSample.isVirtual
  contentMap['isVirtual'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2015-09-22-16:45:30_00003')

  # Attribute CrystalSample.morphology
  currentMap = {}
  contentMap['morphology'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:22:44_00012'] = currentMap
  loadMaps['SAM.CrystalSample.morphology'] = currentMap
  currentMap['tag'] = 'SAM.CrystalSample.morphology'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:22:44_00012'
  currentMap['name'] = 'morphology'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['eType'] = 'cplx'
  currentMap['proc'] = 'direct'
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00035')

  # Attribute CrystalSample.name
  contentMap['name'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-18:22:46_00004')

  # Attribute CrystalSample.ph
  contentMap['ph'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-18:22:46_00005')

  # Attribute CrystalSample.plateIdentifier
  contentMap['plateIdentifier'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2015-06-22-10:30:00_00001')

  # Attribute CrystalSample.rowPosition
  contentMap['rowPosition'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-18:22:41_00004')

  # Attribute CrystalSample.spaceGroup
  currentMap = {}
  contentMap['spaceGroup'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:22:44_00011'] = currentMap
  loadMaps['SAM.CrystalSample.spaceGroup'] = currentMap
  currentMap['tag'] = 'SAM.CrystalSample.spaceGroup'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:22:44_00011'
  currentMap['name'] = 'spaceGroup'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00037')

  # Attribute CrystalSample.subPosition
  contentMap['subPosition'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-18:22:41_00006')

  # Attribute CrystalSample.x
  currentMap = {}
  contentMap['x'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:22:44_00015'] = currentMap
  loadMaps['SAM.CrystalSample.x'] = currentMap
  currentMap['tag'] = 'SAM.CrystalSample.x'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:22:44_00015'
  currentMap['name'] = 'x'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00031')

  # Attribute CrystalSample.y
  currentMap = {}
  contentMap['y'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:22:44_00016'] = currentMap
  loadMaps['SAM.CrystalSample.y'] = currentMap
  currentMap['tag'] = 'SAM.CrystalSample.y'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:22:44_00016'
  currentMap['name'] = 'y'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00031')

  # Attribute CrystalSample.z
  currentMap = {}
  contentMap['z'] = currentMap
  mapsByGuid['www.ccpn.ac.uk_Fogh_2006-08-16-18:22:44_00017'] = currentMap
  loadMaps['SAM.CrystalSample.z'] = currentMap
  currentMap['tag'] = 'SAM.CrystalSample.z'
  currentMap['type'] = 'attr'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-18:22:44_00017'
  currentMap['name'] = 'z'
  currentMap['hicard'] = 1
  currentMap['locard'] = 0
  currentMap['data'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00031')

  # Role CrystalSample.sampleComponents
  contentMap['sampleComponents'] = mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-18:22:46_00001')
  # End of CrystalSample

  currentMap = abstractTypes.get('CrystalSample')
  aList = ['_ID', 'a', 'alpha', 'amount', 'amountUnit', 'b', 'batchIdentifier', 'beta', 'c', 'colPosition', 'creationDate', 'gamma', 'ionicStrength', 'isHazardous', 'isVirtual', 'ph', 'plateIdentifier', 'rowPosition', 'spaceGroup', 'subPosition', 'x', 'y', 'z']
  currentMap['headerAttrs'] = aList
  aList = ['colour', 'crystalType', 'details', 'morphology', 'name']
  currentMap['simpleAttrs'] = aList
  aList = ['sampleComponents', 'applicationData']
  currentMap['cplxAttrs'] = aList
  aList = ['sampleComponents']
  currentMap['children'] = aList

  # Out-of-package link to SampleComponent
  currentMap = {}
  exolinks['SampleComponent'] = currentMap
  loadMaps['SAM.exo-SampleComponent'] = currentMap
  currentMap['tag'] = 'SAM.exo-SampleComponent'
  currentMap['type'] = 'exo'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-14:22:44_00002'
  currentMap['name'] = 'SampleComponent'
  currentMap['eType'] = 'cplx'
  currentMap['class'] = ccpnmodel.ccpncore.api.ccp.lims.Sample.SampleComponent
  aList = list()
  currentMap['keyMaps'] = aList
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2008-06-30-16:30:50_00001'))
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033'))
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033'))
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00037'))

  # Out-of-package link to SampleStore
  currentMap = {}
  exolinks['SampleStore'] = currentMap
  loadMaps['SAM.exo-SampleStore'] = currentMap
  currentMap['tag'] = 'SAM.exo-SampleStore'
  currentMap['type'] = 'exo'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-09-05-12:37:24_00008'
  currentMap['name'] = 'SampleStore'
  currentMap['eType'] = 'cplx'
  currentMap['class'] = ccpnmodel.ccpncore.api.ccp.lims.Sample.SampleStore
  aList = list()
  currentMap['keyMaps'] = aList
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2008-06-30-16:30:50_00001'))

  # Out-of-package link to Sample
  currentMap = {}
  exolinks['Sample'] = currentMap
  loadMaps['SAM.exo-Sample'] = currentMap
  currentMap['tag'] = 'SAM.exo-Sample'
  currentMap['type'] = 'exo'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-14:22:44_00001'
  currentMap['name'] = 'Sample'
  currentMap['eType'] = 'cplx'
  currentMap['class'] = ccpnmodel.ccpncore.api.ccp.lims.Sample.Sample
  aList = list()
  currentMap['keyMaps'] = aList
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2008-06-30-16:30:50_00001'))
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033'))

  # Out-of-package link to CrystalSample
  currentMap = {}
  exolinks['CrystalSample'] = currentMap
  loadMaps['SAM.exo-CrystalSample'] = currentMap
  currentMap['tag'] = 'SAM.exo-CrystalSample'
  currentMap['type'] = 'exo'
  currentMap['guid'] = 'www.ccpn.ac.uk_Fogh_2006-08-16-14:22:44_00004'
  currentMap['name'] = 'CrystalSample'
  currentMap['eType'] = 'cplx'
  currentMap['class'] = ccpnmodel.ccpncore.api.ccp.lims.Sample.CrystalSample
  aList = list()
  currentMap['keyMaps'] = aList
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2008-06-30-16:30:50_00001'))
  aList.append(mapsByGuid.get('www.ccpn.ac.uk_Fogh_2006-08-16-14:22:53_00033'))
